# Configuração do Banco de Dados
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sistema_mecanica?useUnicode=true&characterEncoding=UTF-8
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

# Configuração JPA/Hibernate
  jpa:
    database: postgresql
    show-sql: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
