# Configuração do Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/sistema_mecanica?useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração JPA/Hibernate
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Dialeto do Hibernate para PostgreSQL (opcional, mas recomendado)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
